name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: josedonizetti/tracee-action@44e912d9079685b9f497e3f33cd5ee21dbf35867

    - name: test dns
      run: curl --head http://alura.com

    - name: test sudo
      run: sudo id

    - name: test write
      run: |
        echo "test" > main.go

    - name: test signature
      run: |
        strace ls
        dig xmr.metal3d.org

    - name: Stop and Check Tracee results and create a PR
      uses: josedonizetti/tracee-action@42089b1bb7a9c0fd4e783905548336f26db1f3a1
      with:
        create-pr: "true"
