name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@b1976da90cd5e54d6406aa25ea69b35b7cb052e1

    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Build
      run: go build -o app -v ./...

    - name: test dns
      run: curl --head http://github.com

    - name: Fake upload
      uses: josedonizetti/upload-fake-action@v0.1.0

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@d23db8f001af4a69ed073c76faa8039d9e456424
      with:
        create-pr: "true"
        fail-on-diff: "true"
