name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@75e1af3b1d13912661df029cf5babf6694aca062

    - name: test dns
      run: curl --head http://alura.com

    - name: test sudo
      run: sudo id

    - name: test write
      run: |
        echo "test" > main.go
        git status

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@a402eabf7b623ef140af506628ae33e8ff389f42
      with:
        create-pr: "true"
