name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: josedonizetti/tracee-action@32b97be6a6ea0962f5fd71f005b6ef3395281e5b

    - name: test dns
      run: curl --head http://alura.com

    - name: test sudo
      run: sudo id

    - name: test write
      run: |
        echo "test" > main.go

    - name: test signature
      run: |
        strace ls
        dig xmr.metal3d.org

    - name: Stop and Check Tracee results and create a PR
      uses: josedonizetti/tracee-action@d93a540790f4c2a5f35c8d729d1b4b7f7ffe2d5a
      with:
        create-pr: "true"
