name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: josedonizetti/tracee-action@6b35b31c66a7d9b9f59b4ccf10942332e0c8ff9d

    - name: test dns
      run: curl --head http://alura.com

    - name: test sudo
      run: sudo id

    - name: test write
      run: |
        echo "test" > main.go

    - name: test signature
      run: |
        strace ls
        dig xmr.metal3d.org

    - name: Stop and Check Tracee results and create a PR
      uses: josedonizetti/tracee-action@8a6e73559399c5e3a23417be1e6addd0f0836c46
      with:
        create-pr: "true"
