name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@70205db82c8e37ccef009993f7f87c88da8fa3b2

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -o exe -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@42089b1bb7a9c0fd4e783905548336f26db1f3a1
      with:
        create-pr: "true"
