name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@dbaa12ba6debfcf67c4e78cc81e6c26cef2d2eb1

    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -o exe -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@853e8a6489b5a5dd405fb7e95fc59e0b12f36496
      with:
        fail-on-diff: "true"
        create-pr: "true"
