name: Tracee Pipeline Scan
on: [pull_request]

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: josedonizetti/tracee-action@db34917928438b9f5e2a2c3a21de6b43b62e5992

    - name: Your CI Pipeline Step
      run: for i in {1..20}; do sleep 2; done

    - name: Stop and Check Tracee results and create a PR
      uses: josedonizetti/tracee-action@b41677c5eb55a40652a106c35596259aa9ad4b7e
      with:
        fail-on-diff: "true"
        create-pr: "true"
