name: Tracee Pipeline Scan
on: [pull_request]

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: josedonizetti/tracee-action@a0a28f5bc6aaa37932e40f852e2a68362b9c71c3

    - name: Your CI Pipeline Step
      run: for i in {1..20}; do sleep 2; ps aux; done

    - name: Stop and Check Tracee results and create a PR
      uses: josedonizetti/tracee-action@4244007945a49b16d37583c39344b6ad92ee4676
      with:
        fail-on-diff: "true"
        create-pr: "true"
