name: Tracee Pipeline Scan
on: [pull_request]

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: josedonizetti/tracee-action@8f1a87ec873265b77f8b2cbfb0cb966bdfdfe7f9

    - name: Your CI Pipeline Step
      run: for i in {1..20}; do sleep 2; done

    - name: Stop and Check Tracee results and create a PR
      uses: josedonizetti/tracee-action@6ce7a00942ee100bd994fc49c0245bf9f1a97471
      with:
        fail-on-diff: "true"
        create-pr: "true"
