name: Tracee Pipeline Scan
on: [pull_request]

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: josedonizetti/tracee-action@54954bbce6b5ca4075382e7dfd6c1f89bb53723d

    - name: Your CI Pipeline Step
      run: for i in {1..2}; do sleep 2; ps efx; done

    - name: test dns
      run: curl --head http://aquasecurity.com

    - name: change a file
      run: echo "hello" > hello.txt

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@55bd95e7ac4aa70002f41c53a92548dee26cce24
      with:
        fail-on-diff: "true"
        create-pr: "true"
